In [144]:
import torch 
from torch import nn 
from torchvision import datasets
from torch.utils.data import DataLoader
from torchvision import transforms
import numpy as np
import matplotlib.pyplot as plt 

In [145]:
transform = transforms.ToTensor() 

In [146]:
train_data = datasets.FashionMNIST(
    root = "data",
    train = True,
    download = True,
    transform = transform
)

In [147]:
train_data.data.shape

torch.Size([60000, 28, 28])

In [148]:
np.unique(train_data.targets, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000, 6000]))

In [149]:
test_data = datasets.FashionMNIST(
    root = "data",
    train = False,
    download = True,
    transform = transform
)

In [150]:
test_data.data.shape

torch.Size([10000, 28, 28])

In [151]:
np.unique(test_data.targets, return_counts = True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000]))

In [152]:
train_dataloader = DataLoader(dataset = train_data, batch_size =64)

In [153]:
test_dataloader = DataLoader(dataset = test_data, batch_size = 64)

In [154]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.flatten = nn.Flatten()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(in_features=28*28, out_features=512),

            nn.ReLU(),
            nn.Linear(in_features=512, out_features=512),

            nn.ReLU(),
            nn.Linear(in_features=512, out_features=10)   
        )
    def forward(self, x):
        x = self.flatten(x)
        network = self.linear_relu_stack(x)
        return network

In [155]:
simpleNN = NeuralNetwork()

In [156]:
simpleNN

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)

In [157]:
loss_func = nn.CrossEntropyLoss()

In [158]:
opt = torch.optim.SGD(
    params = simpleNN.parameters(),
    lr = 1e-3
    )

In [159]:
def training(datalodader, model, loss_func, optimizer):

    size = len(datalodader.dataset)

    model.train()

    for batch, (x, y) in enumerate(datalodader):

        pred= model(x)
        loss = loss_func(pred, y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        if batch % 100 == 0:
            loss = loss.item()
            current = batch * len(x)
            print(f"loss: {loss:>5f} at {current:>5d}/{size:>5d}")

In [164]:
def testing(dataloader, model, loss_func):
    size = len(dataloader.dataset)
    num_batch = len(dataloader)

    model.eval()

    test_loss, correct = 0, 0

    with torch.no_grad():
        for x, y in dataloader:
            pred = model(x)
            test_loss += loss_func(pred, y ).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()

    test_loss /= num_batch
    correct /= size

    print(f"\n Test Evaluation: \n Accuracy: {(100 * correct):>5f}%. Avg loss: {test_loss:>5f} \n")

In [161]:
epochs = 5 

In [165]:
for t in range(5):
    print(f"\n\n    Epoch {t+1} ------------- \n")
    training(train_dataloader, simpleNN, loss_func, opt)
    testing(test_dataloader, simpleNN, loss_func)



    Epoch 1 ------------- 

loss: 1.934169 at     0/60000
loss: 1.906756 at  6400/60000
loss: 1.788035 at 12800/60000
loss: 1.839509 at 19200/60000
loss: 1.735669 at 25600/60000
loss: 1.676575 at 32000/60000
loss: 1.704536 at 38400/60000
loss: 1.594568 at 44800/60000
loss: 1.629593 at 51200/60000
loss: 1.527502 at 57600/60000

 Test Evaluation: 
 Accuracy: 61.980000%. Avg loss: 1.542409 



    Epoch 2 ------------- 

loss: 1.601110 at     0/60000
loss: 1.568521 at  6400/60000
loss: 1.415123 at 12800/60000
loss: 1.497010 at 19200/60000
loss: 1.384069 at 25600/60000
loss: 1.368375 at 32000/60000
loss: 1.387501 at 38400/60000
loss: 1.299353 at 44800/60000
loss: 1.348848 at 51200/60000
loss: 1.250399 at 57600/60000

 Test Evaluation: 
 Accuracy: 63.310000%. Avg loss: 1.273625 



    Epoch 3 ------------- 

loss: 1.344434 at     0/60000
loss: 1.328753 at  6400/60000
loss: 1.158534 at 12800/60000
loss: 1.272215 at 19200/60000
loss: 1.154891 at 25600/60000
loss: 1.169110 at 32000/60000
lo